- name: play-01
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: check user exist or not
      command: id expense
      register: user
      ignore_errors: true

    - name: create expense user
      command: useradd expense
      when: user.rc != 0