- name: play-01
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: install mysql service
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx
    - name: restart the nginx
      service:
        name: nginx
        state: started
        enable: yes



