- name: play-01
  hosts: local
  connection: local
  tasks:
  - name: print some info
    debug:
      msg: "This is ravi first program"

  - name: install mysql
    package:
      name: "{{ item }}"
      state: present
    loops:
      - nginx
      - mysql


