- name: play-01
  hosts: local
  connection: local
  become: yes
  become_user: root
  tasks:
    - name: install mysql service
      package:
        name: "{{ item }}"
        state: present
      loop:
        - nginx


