- name: play-01
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: print some info
    debug:
      msg: "This is ravi first program"

  - name: print some info
    debug:
      msg: "This is ravi second program"


