- name: play-01
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: install mysql
      package:
        name: "{{ item }}"
        state: present
      loops:
        - nginx
        - mysql


