- name: play-01
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: install mysql service
      package:
        name: "{{ item }}"
        state: present
        enable: yes
      loop:
        - nginx


