- name: play-01
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: print the facts
      debug:
        msg: "facts are {{ ansible_facts }}"
    - name: install nginx on redhat
      dnf:
        name: nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: install nginx on redhat
      dnf:
        name: nginx
        state: present
      when: ansible_os_family == "ubanto"